/*
 *
 * syscalls.c
 *
 * This file lists all exported syscalls.
 *
 * AUTOMAGICALLY GENERATED BY generate_syscalls.pl - DO NOT MODIFY!
 *
 */

#include <sys/types.h>
#include <sys/device.h>
#include <sys/mailbox.h>
#include <kern/syscall.h>

extern uint32_t ipv4_no;
void exit() { __SYSCALL (SYS_thread,SYS_thread_exit,0,0,0,0); }
void thread_suspend() { __SYSCALL (SYS_thread,SYS_thread_suspend,0,0,0,0); }
void getcurthread() { __SYSCALL (SYS_thread,SYS_thread_getcurthread,0,0,0,0); }
int thread_kill(addr_t addr) { return (int)__SYSCALL (SYS_thread,SYS_thread_kill,addr,0,0,0); }
void thread_switch() { __SYSCALL (SYS_thread,SYS_thread_switch,0,0,0,0); }
uint32_t find_syscall(char* name) { return (uint32_t)__SYSCALL (SYS_thread,SYS_thread_find_syscall,name,0,0,0); }
void putchar(uint8_t ch) { __SYSCALL (SYS_io,SYS_io_putchar,ch,0,0,0); }
uint8_t getchar() { return (uint8_t)__SYSCALL (SYS_io,SYS_io_getchar,0,0,0,0); }
void device_read(struct DEVICE* dev, addr_t addr, void* buf, size_t size) { __SYSCALL (SYS_io,SYS_io_devread,dev,addr,buf,size); }
int register_irq(uint32_t no, void* handler, uint32_t* var) { return (int)__SYSCALL (SYS_module,SYS_module_register_irq,no,handler,var,0); }
int register_device(struct DEVICE* dev) { return (int)__SYSCALL (SYS_module,SYS_module_register_dev,dev,0,0,0); }
int register_pio(addr_t start, size_t count) { return (int)__SYSCALL (SYS_module,SYS_module_register_pio,start,count,0,0); }
int register_lowmem(addr_t start, size_t len) { return (int)__SYSCALL (SYS_module,SYS_module_register_lowmem,start,len,0,0); }
int register_tty(struct DEVICE* dev) { return (int)__SYSCALL (SYS_module,SYS_module_register_tty,dev,0,0,0); }
int register_syscall(char* name, void* func) { return (int)__SYSCALL (SYS_module,SYS_module_register_syscall,name,func,0,0); }
int register_filesystem(struct FILESYSTEM* fs) { return (int)__SYSCALL (SYS_module,SYS_module_register_filesystem,fs,0,0,0); }
int mbox_add(MAILBOX* mbox, uint8_t* ptr, size_t len) { return (int)__SYSCALL (SYS_mbox,SYS_mbox_add,mbox,ptr,len,0); }
int mbox_register(MAILBOX* mbox) { return (int)__SYSCALL (SYS_mbox,SYS_mbox_register,mbox,0,0,0); }
int mbox_fetch(MAILBOX* mbox, uint8_t* ptr, size_t* len) { return (int)__SYSCALL (SYS_mbox,SYS_mbox_fetch,mbox,ptr,len,0); }
int network_add_packet(struct DEVICE* dev, char* pkt, size_t len) { return (int)__SYSCALL (SYS_network,SYS_network_add_packet,dev,pkt,len,0); }
int network_register() { return (int)__SYSCALL (SYS_network,SYS_network_register,0,0,0,0); }
int network_send_packet(struct DEVICE* dev, char* pkt, size_t len) { return (int)__SYSCALL (SYS_network,SYS_network_send_packet,dev,pkt,len,0); }
int mount(char* dev, char* path, char* fstype, uint32_t flags) { return (int)__SYSCALL (SYS_filesys,SYS_filesys_mount,dev,path,fstype,flags); }
void dump_threads() { __SYSCALL (SYS_debug,SYS_debug_dumpthreads,0,0,0,0); }
void dump_devices() { __SYSCALL (SYS_debug,SYS_debug_dumpdevices,0,0,0,0); }
void dump_io() { __SYSCALL (SYS_debug,SYS_debug_dumpio,0,0,0,0); }
void dump_network() { __SYSCALL (SYS_debug,SYS_debug_dumpnetwork,0,0,0,0); }
void dump_syscall() { __SYSCALL (SYS_debug,SYS_debug_dumpsyscall,0,0,0,0); }
void dump_filesys() { __SYSCALL (SYS_debug,SYS_debug_dumpfilesys,0,0,0,0); }
int   debug_argtest(uint32_t r1, uint32_t r2, uint32_t r3, uint32_t r4) { return (int )__SYSCALL (SYS_debug,SYS_debug_argtest,r1,r2,r3,r4); }
void ipv4_debug() { __SYSCALL (ipv4_no,MOD_ipv4_debug,0,0,0,0); }
